### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by rosstopherkeen** [XXIIVV/Monitor#6]
The package.json file is missing, so the app can't be installed. Any way I can get it?

**Comment by joshcho** [comment]
It seems non-web components are no longer supported.

Check out https://github.com/XXIIVV/Clock/tree/164b5f038e6fe86191f91645fe24449698fdf5b0, and do the following.

1. cd Clock/desktop
2. go to package.json and change electron-packager to "^12.1.0"
3. in Clock/desktop run 
npm install
npm run build_osx

That worked for me. Then you should be able to spotlight search Clock.

**Comment by rosstopherkeen** [comment]
Issue solved
